#!/bin/bash

cpuinfo='/proc/cpuinfo'

gawk '
		BEGIN {
			# ':' between one or more spaces, tabs, newlines
			FS = "[ \t\n]+:[ \t\n]+" 
			IGNORECASE = 1
			ORS = " "
			num_of_cores = 0
			num_of_processors = 0
			num_of_cpus = 0
			core_id[0]
			processor_id[0]
			cpu_id[0]
			type = "-"
			iter = 0
		}
		
		# array of logical processors, both HT and physical
		/^processor/ {
			processor_id[iter] = $NF
		}
		
		# array of physical cpus ids
		/^physical/ {
			cpu_id[iter] = $NF
		}
		
		# array of core ids
		/^core id/ {
			core_id[iter] = $NF
			iter++
		}
		END {
			## 	Look thru the array and filter same numbers.
			##	only unique numbers required
			## 	this is to get an accurate count
			##	we are only concerned with array length
			
			i = 0
			## count unique processors ##
			for ( i in processor_id ) {
				procHolder[processor_id[i]] = 1
			}
			for ( i in procHolder ) {				
				num_of_processors++
			}
			
			i = 0
			## count unique physical cpus ##
			for ( i in cpu_id ) {
				cpuHolder[cpu_id[i]] = 1
			}
			for ( i in cpuHolder ) {				
				num_of_cpus++
			}
			
			i = 0		
			## count unique cores ##
			for ( i in core_id ) {
				coreHolder[core_id[i]] = 1
			}
			for ( i in coreHolder ) {				
				num_of_cores++
			}
			
			####################################################################
			# 				algorithm
			# if > 1 processor && processor id (physical id) == core id then Hyperthreaded (HT)
			# if > 1 processor && processor id (physical id) != core id then Multi-Core Processors (MCP)
			# if > 1 processor && processor ids (physical id) > 1 then Multiple Processors (SMP)
			# if = 1 processor then single core/processor Uni-Processor (UP)
			if ( num_of_processors > 1 )
			{
				if ( num_of_processors == (num_of_cores * 2 ))
				{
					type = type "HT-"
				}
				if ( num_of_processors >= num_of_cores )
				{
					type = type "MCP-"
				}
				if ( num_of_cpus > 1 )
				{
					type = type "SMP-"
				}
			} else {
				type = type "UP-"
			}			
			
			print "type " type 
			print "cpu ct " num_of_cpus 
			print "core ct " num_of_cores
			print "proc ct " num_of_processors
		}
		' $cpuinfo
